# Generated by Django 6.0.5 on 2026-06-05 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='phone_number',
        ),
    ]
